import ollama


def generate_ai_summary(
    loan_id,
    risk_result,
    missing_documents,
    payslip_result,
    tax_result,
    bank_result,
    profile_results,
    identity_result
):

    evidence = {
        "loan_id": loan_id,

        "risk": {
            "risk_score": risk_result["risk_score"],
            "risk_level": risk_result["risk_level"],
            "human_review_required": risk_result[
                "human_review_required"
            ]
        },

        "findings": list(
            risk_result["findings"]
        ),

        "missing_documents": list(
            missing_documents
        ),

        "payslip": {
            "status": (
                "VERIFIED"
                if payslip_result
                else "MISSING"
            ),
            "difference_percent": (
                payslip_result["difference_percent"]
                if payslip_result
                else None
            )
        },

        "tax_return": {
            "status": (
                "VERIFIED"
                if tax_result
                else "MISSING"
            ),
            "difference_percent": (
                tax_result["difference_percent"]
                if tax_result
                else None
            )
        },

        "bank_assets": {
            "dataset_value": (
                bank_result["dataset_bank_assets"]
                if bank_result
                else None
            ),
            "document_value": (
                bank_result["document_bank_assets"]
                if bank_result
                else None
            ),
            "difference_percent": (
                bank_result["difference_percent"]
                if bank_result
                else None
            )
        },

        "profile": [
            {
                "check": result["check"],
                "match": result["match"]
            }
            for result in profile_results
        ],

        "identity": {
            "status": identity_result["status"]
        }
    }

    prompt = f"""
You are LoanLens, an AI assistant for loan document review.

You are given VERIFIED evidence generated by a deterministic
document verification system.

Your ONLY job is to explain the supplied evidence clearly
to a human loan officer.

The deterministic verification system is the SOURCE OF TRUTH.

STRICT RULES:

1. Use ONLY facts explicitly present in VERIFIED EVIDENCE.

2. NEVER invent numbers, names, dates, percentages,
   document contents, financial values, or findings.

3. NEVER add a currency such as INR, USD, RMB, or EUR.

4. NEVER perform additional calculations.

5. NEVER calculate absolute differences.

6. NEVER convert monthly income into annual income.

7. NEVER infer fraud, criminal activity, or intent.

8. NEVER approve or reject the loan.

9. NEVER change the supplied risk score or risk level.

10. NEVER contradict the "findings" field.

11. If the "findings" field contains one or more findings,
    ALL of those findings MUST appear under KEY FINDINGS.

12. If the "findings" field is empty, write:
    "No significant issues detected."

13. If "missing_documents" contains documents, those documents
    MUST be mentioned under DOCUMENT ISSUES.

14. A missing document MUST NOT be described as verified.

15. If a verification result is unavailable, write:
    "Not available in the verified evidence."

16. Recommendations must be based ONLY on the supplied findings
    and human_review_required value.

17. Do not recommend investigating information that is not
    present in the verified evidence.

18. Do not add extra sections.

19. Keep the report concise and professional.

IMPORTANT:

The following finding is authoritative:

{risk_result["findings"]}

If the finding is:

"Missing document: tax_return"

then KEY FINDINGS MUST mention:

"Missing document: tax_return"

If the finding is:

"Payslip income mismatch"

then KEY FINDINGS MUST mention:

"Payslip income mismatch"

If the finding is:

"Tax return income mismatch"

then KEY FINDINGS MUST mention:

"Tax return income mismatch"

If the finding is:

"Bank asset mismatch"

then KEY FINDINGS MUST mention:

"Bank asset mismatch"

If the finding is:

"Identity mismatch across documents"

then KEY FINDINGS MUST mention:

"Identity mismatch across documents"

Generate EXACTLY these sections:

EXECUTIVE SUMMARY

KEY FINDINGS

DOCUMENT ISSUES

FINANCIAL CONSISTENCY

IDENTITY AND PROFILE CONSISTENCY

RECOMMENDED HUMAN ACTION

For numerical findings, repeat ONLY the exact numbers
provided in the verified evidence.

VERIFIED EVIDENCE:

{evidence}
"""

    response = ollama.chat(
        model="qwen2:7b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"]